prompts:
  - "Напиши текст песни в жанре {genre} с {mood} настроением. Тема: '{theme}'. Аудитория: {audience}. В тексте песни рифма {rhyme}. Что касается длины: количество куплетов - {verses}, количество припевов - {choruses}."

providers:
  - id: python:./providers/custom_providers.py:mistral_handler
    label: "Mistral-Medium"
    config:
      api_key: "{{env.MISTRAL_API_KEY}}"
      model: "mistral-medium"

  - id: python:./providers/custom_providers.py:claude_handler
    label: "Claude-3-Sonnet"
    config:
      api_key: "{{env.ANTHROPIC_API_KEY}}"
      model: "claude-3-sonnet-20240229"

  - id: python:./providers/custom_providers.py:groq_handler
    label: "Groq-Mixtral"
    config:
      api_key: "{{env.GROQ_API_KEY}}"
      model: "mixtral-8x7b-32768"

vars:
  theme: "{{user_input}}"
  genre: ["рэп", "рок", "поп", "хип-хоп"]
  mood: ["веселым", "грустным", "энергичным", "спокойным"]
  audience: ["дети", "молодежь", "взрослые", "без разницы"]
  rhyme: ["должна быть", "отсутствует", "может как быть, так и не быть"]
  verses: ["1", "2", "3", "4", "5", "без разницы"]
  choruses: ["1", "2", "3", "4", "5", "без разницы"]

metrics:
  - type: "ai"
    name: "Креативность"
    prompt: |
      Оцени от 1 до 10 креативность текста по критериям:
      1. Оригинальность идеи
      2. Неожиданные метафоры/образы
      3. Нетипичные рифмы (для жанра {genre})
      4. Эмоциональная глубина

  - type: "ai"
    name: "Соответствие запросу"
    prompt: |
      Оцени от 1 до 10 насколько текст соответствует:
      1. Жанру: {genre}
      2. Настроению: {mood}
      3. Аудитории: {audience}
      4. Техническим требованиям (куплетов {verses} штук/припевов {choruses} штук, присутствуие рифмы: {rhyme})

tests:
  - description: "Тест работы провайдеров"
    vars:
      theme: "Выходной с семьей в уютном кафе"
      genre: "поп"
      mood: "спокойным"
      audience: "взрослые"
      rhyme: "может как быть, так и не быть"
      verses: "2"
      choruses: "2"